Fix Docker build process on ARM chips (GCC for pip install)
cityofaustin/atd-bond-reporting pull request #4
Opened 2023-06-12 12:38 UTC by frankhereford

## Intent

While reviewing @Charlie-Henry's PR #3, I found that I wasn't able to build the docker image locally for testing on my M1 Mac. Interestingly, on an Intel machine, it does build, which explains why the GitHub action has not been failing. 

My best guess without running down a rabbit hole about the cause of this is that on M1, the python package requires supporting libraries to be built because they are not natively available. However, they are on the Intel image so it doesn't have to use `gcc` to build them. 🤔

This PR has a few changes to the Dockerfile so that it builds both on Intel and modern Macs.

## Testing

This can be tested by issuing the same command in the root of this checkout on a Mac and on an intel machine (I've used `atd-data03`) and see that it completes.

```
docker build --no-cache -t bond-reporting .
```

## Extra commits in PR?

I accidentally started this branch off from Charlies `ch-quarterly-reports` which had his commits in it that you can find in PR #3. I reverted those back out to get to a clean, empty branch and then put my Dockerfile change in.

2023-06-15 15:22 UTC, frankhereford commented
@Charlie-Henry and I slacked about this for a bit this morning. Charlie, please feel free to merge or close or whatever is best for you. Thanks!

2023-06-15 16:40 UTC, Charlie-Henry requested changes
Just going to request changes here so we don't accidentally merge this as python 3.10 does indeed break the microstrategy ETLs

2023-09-01 18:38 UTC, johnclary approved these changes

2023-09-01 18:38 UTC, merged

2023-09-01 18:38 UTC, johnclary commented
Let's try this!